/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface BasicConfiguration
 */
export interface BasicConfiguration {
  /**
   *
   * @type {BasicConfigurationCurrencyEnum}
   * @memberof BasicConfiguration
   */
  currency?: BasicConfigurationCurrencyEnum;
  /**
   * Activate or desactivate login without password or not
   * @type {boolean}
   * @memberof BasicConfiguration
   */
  loginWithoutPassword?: boolean;
}

/**
 * @export
 */
export const BasicConfigurationCurrencyEnum = {
  Mga: "MGA",
  Usd: "USD",
  Eur: "EUR",
} as const;
export type BasicConfigurationCurrencyEnum = (typeof BasicConfigurationCurrencyEnum)[keyof typeof BasicConfigurationCurrencyEnum];

/**
 * Check if a given object implements the BasicConfiguration interface.
 */
export function instanceOfBasicConfiguration(value: object): value is BasicConfiguration {
  return true;
}

export function BasicConfigurationFromJSON(json: any): BasicConfiguration {
  return BasicConfigurationFromJSONTyped(json, false);
}

export function BasicConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicConfiguration {
  if (json == null) {
    return json;
  }
  return {
    currency: json["currency"] == null ? undefined : json["currency"],
    loginWithoutPassword: json["loginWithoutPassword"] == null ? undefined : json["loginWithoutPassword"],
  };
}

export function BasicConfigurationToJSON(json: any): BasicConfiguration {
  return BasicConfigurationToJSONTyped(json, false);
}

export function BasicConfigurationToJSONTyped(value?: BasicConfiguration | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    currency: value["currency"],
    loginWithoutPassword: value["loginWithoutPassword"],
  };
}
