/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ConfigurationAllOfSubscription
 */
export interface ConfigurationAllOfSubscription {
  /**
   *
   * @type {boolean}
   * @memberof ConfigurationAllOfSubscription
   */
  isActive?: boolean;
  /**
   *
   * @type {Date}
   * @memberof ConfigurationAllOfSubscription
   */
  endingDate?: Date;
}

/**
 * Check if a given object implements the ConfigurationAllOfSubscription interface.
 */
export function instanceOfConfigurationAllOfSubscription(value: object): value is ConfigurationAllOfSubscription {
  return true;
}

export function ConfigurationAllOfSubscriptionFromJSON(json: any): ConfigurationAllOfSubscription {
  return ConfigurationAllOfSubscriptionFromJSONTyped(json, false);
}

export function ConfigurationAllOfSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationAllOfSubscription {
  if (json == null) {
    return json;
  }
  return {
    isActive: json["isActive"] == null ? undefined : json["isActive"],
    endingDate: json["endingDate"] == null ? undefined : new Date(json["endingDate"]),
  };
}

export function ConfigurationAllOfSubscriptionToJSON(json: any): ConfigurationAllOfSubscription {
  return ConfigurationAllOfSubscriptionToJSONTyped(json, false);
}

export function ConfigurationAllOfSubscriptionToJSONTyped(value?: ConfigurationAllOfSubscription | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    isActive: value["isActive"],
    endingDate: value["endingDate"] == null ? value["endingDate"] : value["endingDate"].toISOString(),
  };
}
