/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Label } from "./Label";
import { LabelFromJSON, LabelFromJSONTyped, LabelToJSON, LabelToJSONTyped } from "./Label";

/**
 *
 * @export
 * @interface CreationTransaction
 */
export interface CreationTransaction {
  /**
   *
   * @type {Date}
   * @memberof CreationTransaction
   */
  date?: Date;
  /**
   *
   * @type {Array<Label>}
   * @memberof CreationTransaction
   */
  labels?: Array<Label>;
  /**
   *
   * @type {CreationTransactionTypeEnum}
   * @memberof CreationTransaction
   */
  type?: CreationTransactionTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CreationTransaction
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof CreationTransaction
   */
  amount?: number;
  /**
   *
   * @type {string}
   * @memberof CreationTransaction
   */
  walletId?: string;
  /**
   *
   * @type {string}
   * @memberof CreationTransaction
   */
  accountId?: string;
  /**
   *
   * @type {string}
   * @memberof CreationTransaction
   */
  goalId?: string;
}

/**
 * @export
 */
export const CreationTransactionTypeEnum = {
  In: "IN",
  Out: "OUT",
} as const;
export type CreationTransactionTypeEnum = (typeof CreationTransactionTypeEnum)[keyof typeof CreationTransactionTypeEnum];

/**
 * Check if a given object implements the CreationTransaction interface.
 */
export function instanceOfCreationTransaction(value: object): value is CreationTransaction {
  return true;
}

export function CreationTransactionFromJSON(json: any): CreationTransaction {
  return CreationTransactionFromJSONTyped(json, false);
}

export function CreationTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationTransaction {
  if (json == null) {
    return json;
  }
  return {
    date: json["date"] == null ? undefined : new Date(json["date"]),
    labels: json["labels"] == null ? undefined : (json["labels"] as Array<any>).map(LabelFromJSON),
    type: json["type"] == null ? undefined : json["type"],
    description: json["description"] == null ? undefined : json["description"],
    amount: json["amount"] == null ? undefined : json["amount"],
    walletId: json["walletId"] == null ? undefined : json["walletId"],
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    goalId: json["goalId"] == null ? undefined : json["goalId"],
  };
}

export function CreationTransactionToJSON(json: any): CreationTransaction {
  return CreationTransactionToJSONTyped(json, false);
}

export function CreationTransactionToJSONTyped(value?: CreationTransaction | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    date: value["date"] == null ? value["date"] : value["date"].toISOString(),
    labels: value["labels"] == null ? undefined : (value["labels"] as Array<any>).map(LabelToJSON),
    type: value["type"],
    description: value["description"],
    amount: value["amount"],
    walletId: value["walletId"],
    accountId: value["accountId"],
    goalId: value["goalId"],
  };
}
