/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreationProject
 */
export interface CreationProject {
  /**
   *
   * @type {string}
   * @memberof CreationProject
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CreationProject
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof CreationProject
   */
  initialBudget?: number;
  /**
   *
   * @type {string}
   * @memberof CreationProject
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof CreationProject
   */
  iconRef?: string;
}

/**
 * Check if a given object implements the CreationProject interface.
 */
export function instanceOfCreationProject(value: object): value is CreationProject {
  return true;
}

export function CreationProjectFromJSON(json: any): CreationProject {
  return CreationProjectFromJSONTyped(json, false);
}

export function CreationProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationProject {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    initialBudget: json["initialBudget"] == null ? undefined : json["initialBudget"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
  };
}

export function CreationProjectToJSON(json: any): CreationProject {
  return CreationProjectToJSONTyped(json, false);
}

export function CreationProjectToJSONTyped(value?: CreationProject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    initialBudget: value["initialBudget"],
    color: value["color"],
    iconRef: value["iconRef"],
  };
}
