/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreationWallet
 */
export interface CreationWallet {
  /**
   *
   * @type {string}
   * @memberof CreationWallet
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CreationWallet
   */
  description?: string;
  /**
   *
   * @type {CreationWalletTypeEnum}
   * @memberof CreationWallet
   */
  type?: CreationWalletTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CreationWallet
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof CreationWallet
   */
  iconRef?: string;
}

/**
 * @export
 */
export const CreationWalletTypeEnum = {
  Cash: "CASH",
  MobileMoney: "MOBILE_MONEY",
  Bank: "BANK",
  Debt: "DEBT",
} as const;
export type CreationWalletTypeEnum = (typeof CreationWalletTypeEnum)[keyof typeof CreationWalletTypeEnum];

/**
 * Check if a given object implements the CreationWallet interface.
 */
export function instanceOfCreationWallet(value: object): value is CreationWallet {
  return true;
}

export function CreationWalletFromJSON(json: any): CreationWallet {
  return CreationWalletFromJSONTyped(json, false);
}

export function CreationWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationWallet {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    type: json["type"] == null ? undefined : json["type"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
  };
}

export function CreationWalletToJSON(json: any): CreationWallet {
  return CreationWalletToJSONTyped(json, false);
}

export function CreationWalletToJSONTyped(value?: CreationWallet | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    type: value["type"],
    color: value["color"],
    iconRef: value["iconRef"],
  };
}
