/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreationLabel
 */
export interface CreationLabel {
  /**
   *
   * @type {string}
   * @memberof CreationLabel
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CreationLabel
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof CreationLabel
   */
  iconRef?: string;
}

/**
 * Check if a given object implements the CreationLabel interface.
 */
export function instanceOfCreationLabel(value: object): value is CreationLabel {
  return true;
}

export function CreationLabelFromJSON(json: any): CreationLabel {
  return CreationLabelFromJSONTyped(json, false);
}

export function CreationLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationLabel {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
  };
}

export function CreationLabelToJSON(json: any): CreationLabel {
  return CreationLabelToJSONTyped(json, false);
}

export function CreationLabelToJSONTyped(value?: CreationLabel | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    color: value["color"],
    iconRef: value["iconRef"],
  };
}
