/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreationGoal
 */
export interface CreationGoal {
  /**
   *
   * @type {string}
   * @memberof CreationGoal
   */
  accountId?: string;
  /**
   *
   * @type {string}
   * @memberof CreationGoal
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof CreationGoal
   */
  amount?: number;
  /**
   *
   * @type {string}
   * @memberof CreationGoal
   */
  walletId?: string;
  /**
   *
   * @type {Date}
   * @memberof CreationGoal
   */
  startingDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof CreationGoal
   */
  endingDate?: Date;
  /**
   *
   * @type {string}
   * @memberof CreationGoal
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof CreationGoal
   */
  iconRef?: string;
}

/**
 * Check if a given object implements the CreationGoal interface.
 */
export function instanceOfCreationGoal(value: object): value is CreationGoal {
  return true;
}

export function CreationGoalFromJSON(json: any): CreationGoal {
  return CreationGoalFromJSONTyped(json, false);
}

export function CreationGoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationGoal {
  if (json == null) {
    return json;
  }
  return {
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    name: json["name"] == null ? undefined : json["name"],
    amount: json["amount"] == null ? undefined : json["amount"],
    walletId: json["walletId"] == null ? undefined : json["walletId"],
    startingDate: json["startingDate"] == null ? undefined : new Date(json["startingDate"]),
    endingDate: json["endingDate"] == null ? undefined : new Date(json["endingDate"]),
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
  };
}

export function CreationGoalToJSON(json: any): CreationGoal {
  return CreationGoalToJSONTyped(json, false);
}

export function CreationGoalToJSONTyped(value?: CreationGoal | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    accountId: value["accountId"],
    name: value["name"],
    amount: value["amount"],
    walletId: value["walletId"],
    startingDate: value["startingDate"] == null ? value["startingDate"] : value["startingDate"].toISOString(),
    endingDate: value["endingDate"] == null ? value["endingDate"] : value["endingDate"].toISOString(),
    color: value["color"],
    iconRef: value["iconRef"],
  };
}
