/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreationProjectTransaction
 */
export interface CreationProjectTransaction {
  /**
   *
   * @type {string}
   * @memberof CreationProjectTransaction
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CreationProjectTransaction
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof CreationProjectTransaction
   */
  estimatedCost?: number;
  /**
   *
   * @type {number}
   * @memberof CreationProjectTransaction
   */
  realCost?: number;
  /**
   * ID du wallet pour déduire le coût réel
   * @type {string}
   * @memberof CreationProjectTransaction
   */
  walletId?: string;
}

/**
 * Check if a given object implements the CreationProjectTransaction interface.
 */
export function instanceOfCreationProjectTransaction(value: object): value is CreationProjectTransaction {
  return true;
}

export function CreationProjectTransactionFromJSON(json: any): CreationProjectTransaction {
  return CreationProjectTransactionFromJSONTyped(json, false);
}

export function CreationProjectTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationProjectTransaction {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    estimatedCost: json["estimatedCost"] == null ? undefined : json["estimatedCost"],
    realCost: json["realCost"] == null ? undefined : json["realCost"],
    walletId: json["walletId"] == null ? undefined : json["walletId"],
  };
}

export function CreationProjectTransactionToJSON(json: any): CreationProjectTransaction {
  return CreationProjectTransactionToJSONTyped(json, false);
}

export function CreationProjectTransactionToJSONTyped(value?: CreationProjectTransaction | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    estimatedCost: value["estimatedCost"],
    realCost: value["realCost"],
    walletId: value["walletId"],
  };
}
