/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Goal } from "./Goal";
import { GoalFromJSON, GoalFromJSONTyped, GoalToJSON, GoalToJSONTyped } from "./Goal";
import type { PaginationResult } from "./PaginationResult";
import { PaginationResultFromJSON, PaginationResultFromJSONTyped, PaginationResultToJSON, PaginationResultToJSONTyped } from "./PaginationResult";

/**
 *
 * @export
 * @interface GetAllGoals200Response
 */
export interface GetAllGoals200Response {
  /**
   *
   * @type {PaginationResult}
   * @memberof GetAllGoals200Response
   */
  pagination?: PaginationResult;
  /**
   *
   * @type {Array<Goal>}
   * @memberof GetAllGoals200Response
   */
  values?: Array<Goal>;
}

/**
 * Check if a given object implements the GetAllGoals200Response interface.
 */
export function instanceOfGetAllGoals200Response(value: object): value is GetAllGoals200Response {
  return true;
}

export function GetAllGoals200ResponseFromJSON(json: any): GetAllGoals200Response {
  return GetAllGoals200ResponseFromJSONTyped(json, false);
}

export function GetAllGoals200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllGoals200Response {
  if (json == null) {
    return json;
  }
  return {
    pagination: json["pagination"] == null ? undefined : PaginationResultFromJSON(json["pagination"]),
    values: json["values"] == null ? undefined : (json["values"] as Array<any>).map(GoalFromJSON),
  };
}

export function GetAllGoals200ResponseToJSON(json: any): GetAllGoals200Response {
  return GetAllGoals200ResponseToJSONTyped(json, false);
}

export function GetAllGoals200ResponseToJSONTyped(value?: GetAllGoals200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    pagination: PaginationResultToJSON(value["pagination"]),
    values: value["values"] == null ? undefined : (value["values"] as Array<any>).map(GoalToJSON),
  };
}
