/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Label } from "./Label";
import { LabelFromJSON, LabelFromJSONTyped, LabelToJSON, LabelToJSONTyped } from "./Label";
import type { PaginationResult } from "./PaginationResult";
import { PaginationResultFromJSON, PaginationResultFromJSONTyped, PaginationResultToJSON, PaginationResultToJSONTyped } from "./PaginationResult";

/**
 *
 * @export
 * @interface GetAllLabels200Response
 */
export interface GetAllLabels200Response {
  /**
   *
   * @type {PaginationResult}
   * @memberof GetAllLabels200Response
   */
  pagination?: PaginationResult;
  /**
   *
   * @type {Array<Label>}
   * @memberof GetAllLabels200Response
   */
  values?: Array<Label>;
}

/**
 * Check if a given object implements the GetAllLabels200Response interface.
 */
export function instanceOfGetAllLabels200Response(value: object): value is GetAllLabels200Response {
  return true;
}

export function GetAllLabels200ResponseFromJSON(json: any): GetAllLabels200Response {
  return GetAllLabels200ResponseFromJSONTyped(json, false);
}

export function GetAllLabels200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllLabels200Response {
  if (json == null) {
    return json;
  }
  return {
    pagination: json["pagination"] == null ? undefined : PaginationResultFromJSON(json["pagination"]),
    values: json["values"] == null ? undefined : (json["values"] as Array<any>).map(LabelFromJSON),
  };
}

export function GetAllLabels200ResponseToJSON(json: any): GetAllLabels200Response {
  return GetAllLabels200ResponseToJSONTyped(json, false);
}

export function GetAllLabels200ResponseToJSONTyped(value?: GetAllLabels200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    pagination: PaginationResultToJSON(value["pagination"]),
    values: value["values"] == null ? undefined : (value["values"] as Array<any>).map(LabelToJSON),
  };
}
