/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { PaginationResult } from "./PaginationResult";
import { PaginationResultFromJSON, PaginationResultFromJSONTyped, PaginationResultToJSON, PaginationResultToJSONTyped } from "./PaginationResult";
import type { Wallet } from "./Wallet";
import { WalletFromJSON, WalletFromJSONTyped, WalletToJSON, WalletToJSONTyped } from "./Wallet";

/**
 *
 * @export
 * @interface GetAllWallets200Response
 */
export interface GetAllWallets200Response {
  /**
   *
   * @type {PaginationResult}
   * @memberof GetAllWallets200Response
   */
  pagination?: PaginationResult;
  /**
   *
   * @type {Array<Wallet>}
   * @memberof GetAllWallets200Response
   */
  values?: Array<Wallet>;
}

/**
 * Check if a given object implements the GetAllWallets200Response interface.
 */
export function instanceOfGetAllWallets200Response(value: object): value is GetAllWallets200Response {
  return true;
}

export function GetAllWallets200ResponseFromJSON(json: any): GetAllWallets200Response {
  return GetAllWallets200ResponseFromJSONTyped(json, false);
}

export function GetAllWallets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllWallets200Response {
  if (json == null) {
    return json;
  }
  return {
    pagination: json["pagination"] == null ? undefined : PaginationResultFromJSON(json["pagination"]),
    values: json["values"] == null ? undefined : (json["values"] as Array<any>).map(WalletFromJSON),
  };
}

export function GetAllWallets200ResponseToJSON(json: any): GetAllWallets200Response {
  return GetAllWallets200ResponseToJSONTyped(json, false);
}

export function GetAllWallets200ResponseToJSONTyped(value?: GetAllWallets200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    pagination: PaginationResultToJSON(value["pagination"]),
    values: value["values"] == null ? undefined : (value["values"] as Array<any>).map(WalletToJSON),
  };
}
