/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface GoogleSignInRequest
 */
export interface GoogleSignInRequest {
  /**
   *
   * @type {string}
   * @memberof GoogleSignInRequest
   */
  idToken?: string;
}

/**
 * Check if a given object implements the GoogleSignInRequest interface.
 */
export function instanceOfGoogleSignInRequest(value: object): value is GoogleSignInRequest {
  return true;
}

export function GoogleSignInRequestFromJSON(json: any): GoogleSignInRequest {
  return GoogleSignInRequestFromJSONTyped(json, false);
}

export function GoogleSignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleSignInRequest {
  if (json == null) {
    return json;
  }
  return {
    idToken: json["idToken"] == null ? undefined : json["idToken"],
  };
}

export function GoogleSignInRequestToJSON(json: any): GoogleSignInRequest {
  return GoogleSignInRequestToJSONTyped(json, false);
}

export function GoogleSignInRequestToJSONTyped(value?: GoogleSignInRequest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    idToken: value["idToken"],
  };
}
