/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Label
 */
export interface Label {
  /**
   *
   * @type {string}
   * @memberof Label
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  iconRef?: string;
  /**
   *
   * @type {string}
   * @memberof Label
   */
  id?: string;
}

/**
 * Check if a given object implements the Label interface.
 */
export function instanceOfLabel(value: object): value is Label {
  return true;
}

export function LabelFromJSON(json: any): Label {
  return LabelFromJSONTyped(json, false);
}

export function LabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Label {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
    id: json["id"] == null ? undefined : json["id"],
  };
}

export function LabelToJSON(json: any): Label {
  return LabelToJSONTyped(json, false);
}

export function LabelToJSONTyped(value?: Label | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    color: value["color"],
    iconRef: value["iconRef"],
    id: value["id"],
  };
}
