/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { ConfigurationAllOfSubscription } from "./ConfigurationAllOfSubscription";
import {
  ConfigurationAllOfSubscriptionFromJSON,
  ConfigurationAllOfSubscriptionFromJSONTyped,
  ConfigurationAllOfSubscriptionToJSON,
  ConfigurationAllOfSubscriptionToJSONTyped,
} from "./ConfigurationAllOfSubscription";
import type { TransactionConfiguration } from "./TransactionConfiguration";
import {
  TransactionConfigurationFromJSON,
  TransactionConfigurationFromJSONTyped,
  TransactionConfigurationToJSON,
  TransactionConfigurationToJSONTyped,
} from "./TransactionConfiguration";

/**
 *
 * @export
 * @interface ModelConfiguration
 */
export interface ModelConfiguration {
  /**
   *
   * @type {ModelConfigurationCurrencyEnum}
   * @memberof ModelConfiguration
   */
  currency?: ModelConfigurationCurrencyEnum;
  /**
   * Activate or desactivate login without password or not
   * @type {boolean}
   * @memberof ModelConfiguration
   */
  loginWithoutPassword?: boolean;
  /**
   *
   * @type {TransactionConfiguration}
   * @memberof ModelConfiguration
   */
  transaction?: TransactionConfiguration;
  /**
   *
   * @type {ConfigurationAllOfSubscription}
   * @memberof ModelConfiguration
   */
  subscription?: ConfigurationAllOfSubscription;
}

/**
 * @export
 */
export const ModelConfigurationCurrencyEnum = {
  Mga: "MGA",
  Usd: "USD",
  Eur: "EUR",
} as const;
export type ModelConfigurationCurrencyEnum = (typeof ModelConfigurationCurrencyEnum)[keyof typeof ModelConfigurationCurrencyEnum];

/**
 * Check if a given object implements the ModelConfiguration interface.
 */
export function instanceOfModelConfiguration(value: object): value is ModelConfiguration {
  return true;
}

export function ModelConfigurationFromJSON(json: any): ModelConfiguration {
  return ModelConfigurationFromJSONTyped(json, false);
}

export function ModelConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelConfiguration {
  if (json == null) {
    return json;
  }
  return {
    currency: json["currency"] == null ? undefined : json["currency"],
    loginWithoutPassword: json["loginWithoutPassword"] == null ? undefined : json["loginWithoutPassword"],
    transaction: json["transaction"] == null ? undefined : TransactionConfigurationFromJSON(json["transaction"]),
    subscription: json["subscription"] == null ? undefined : ConfigurationAllOfSubscriptionFromJSON(json["subscription"]),
  };
}

export function ModelConfigurationToJSON(json: any): ModelConfiguration {
  return ModelConfigurationToJSONTyped(json, false);
}

export function ModelConfigurationToJSONTyped(value?: ModelConfiguration | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    currency: value["currency"],
    loginWithoutPassword: value["loginWithoutPassword"],
    transaction: TransactionConfigurationToJSON(value["transaction"]),
    subscription: ConfigurationAllOfSubscriptionToJSON(value["subscription"]),
  };
}
