/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface PaginationResult
 */
export interface PaginationResult {
  /**
   *
   * @type {number}
   * @memberof PaginationResult
   */
  totalPage?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationResult
   */
  page?: number;
  /**
   *
   * @type {boolean}
   * @memberof PaginationResult
   */
  hasNext?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PaginationResult
   */
  hasPrev?: boolean;
}

/**
 * Check if a given object implements the PaginationResult interface.
 */
export function instanceOfPaginationResult(value: object): value is PaginationResult {
  return true;
}

export function PaginationResultFromJSON(json: any): PaginationResult {
  return PaginationResultFromJSONTyped(json, false);
}

export function PaginationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResult {
  if (json == null) {
    return json;
  }
  return {
    totalPage: json["totalPage"] == null ? undefined : json["totalPage"],
    page: json["page"] == null ? undefined : json["page"],
    hasNext: json["hasNext"] == null ? undefined : json["hasNext"],
    hasPrev: json["hasPrev"] == null ? undefined : json["hasPrev"],
  };
}

export function PaginationResultToJSON(json: any): PaginationResult {
  return PaginationResultToJSONTyped(json, false);
}

export function PaginationResultToJSONTyped(value?: PaginationResult | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    totalPage: value["totalPage"],
    page: value["page"],
    hasNext: value["hasNext"],
    hasPrev: value["hasPrev"],
  };
}
