/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Project
 */
export interface Project {
  /**
   *
   * @type {string}
   * @memberof Project
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof Project
   */
  initialBudget?: number;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  iconRef?: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  accountId?: string;
  /**
   *
   * @type {Date}
   * @memberof Project
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof Project
   */
  updatedAt?: Date;
  /**
   *
   * @type {boolean}
   * @memberof Project
   */
  isArchived?: boolean;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
  return true;
}

export function ProjectFromJSON(json: any): Project {
  return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    initialBudget: json["initialBudget"] == null ? undefined : json["initialBudget"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
    id: json["id"] == null ? undefined : json["id"],
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    updatedAt: json["updatedAt"] == null ? undefined : new Date(json["updatedAt"]),
    isArchived: json["isArchived"] == null ? undefined : json["isArchived"],
  };
}

export function ProjectToJSON(json: any): Project {
  return ProjectToJSONTyped(json, false);
}

export function ProjectToJSONTyped(value?: Project | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    initialBudget: value["initialBudget"],
    color: value["color"],
    iconRef: value["iconRef"],
    id: value["id"],
    accountId: value["accountId"],
    createdAt: value["createdAt"] == null ? value["createdAt"] : value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
    isArchived: value["isArchived"],
  };
}
