/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ProjectTransaction
 */
export interface ProjectTransaction {
  /**
   *
   * @type {string}
   * @memberof ProjectTransaction
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectTransaction
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof ProjectTransaction
   */
  estimatedCost?: number;
  /**
   *
   * @type {number}
   * @memberof ProjectTransaction
   */
  realCost?: number;
  /**
   *
   * @type {string}
   * @memberof ProjectTransaction
   */
  walletId?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectTransaction
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectTransaction
   */
  projectId?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectTransaction
   */
  accountId?: string;
  /**
   *
   * @type {Date}
   * @memberof ProjectTransaction
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ProjectTransaction
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the ProjectTransaction interface.
 */
export function instanceOfProjectTransaction(value: object): value is ProjectTransaction {
  return true;
}

export function ProjectTransactionFromJSON(json: any): ProjectTransaction {
  return ProjectTransactionFromJSONTyped(json, false);
}

export function ProjectTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectTransaction {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    estimatedCost: json["estimatedCost"] == null ? undefined : json["estimatedCost"],
    realCost: json["realCost"] == null ? undefined : json["realCost"],
    walletId: json["walletId"] == null ? undefined : json["walletId"],
    id: json["id"] == null ? undefined : json["id"],
    projectId: json["projectId"] == null ? undefined : json["projectId"],
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    updatedAt: json["updatedAt"] == null ? undefined : new Date(json["updatedAt"]),
  };
}

export function ProjectTransactionToJSON(json: any): ProjectTransaction {
  return ProjectTransactionToJSONTyped(json, false);
}

export function ProjectTransactionToJSONTyped(value?: ProjectTransaction | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    estimatedCost: value["estimatedCost"],
    realCost: value["realCost"],
    walletId: value["walletId"],
    id: value["id"],
    projectId: value["projectId"],
    accountId: value["accountId"],
    createdAt: value["createdAt"] == null ? value["createdAt"] : value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
  };
}
