/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Project } from "./Project";
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON, ProjectToJSONTyped } from "./Project";

/**
 *
 * @export
 * @interface ProjectStatistics
 */
export interface ProjectStatistics {
  /**
   *
   * @type {Project}
   * @memberof ProjectStatistics
   */
  project?: Project;
  /**
   *
   * @type {number}
   * @memberof ProjectStatistics
   */
  totalEstimatedCost?: number;
  /**
   *
   * @type {number}
   * @memberof ProjectStatistics
   */
  totalRealCost?: number;
  /**
   *
   * @type {number}
   * @memberof ProjectStatistics
   */
  remainingBudget?: number;
  /**
   *
   * @type {number}
   * @memberof ProjectStatistics
   */
  transactionCount?: number;
}

/**
 * Check if a given object implements the ProjectStatistics interface.
 */
export function instanceOfProjectStatistics(value: object): value is ProjectStatistics {
  return true;
}

export function ProjectStatisticsFromJSON(json: any): ProjectStatistics {
  return ProjectStatisticsFromJSONTyped(json, false);
}

export function ProjectStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectStatistics {
  if (json == null) {
    return json;
  }
  return {
    project: json["project"] == null ? undefined : ProjectFromJSON(json["project"]),
    totalEstimatedCost: json["totalEstimatedCost"] == null ? undefined : json["totalEstimatedCost"],
    totalRealCost: json["totalRealCost"] == null ? undefined : json["totalRealCost"],
    remainingBudget: json["remainingBudget"] == null ? undefined : json["remainingBudget"],
    transactionCount: json["transactionCount"] == null ? undefined : json["transactionCount"],
  };
}

export function ProjectStatisticsToJSON(json: any): ProjectStatistics {
  return ProjectStatisticsToJSONTyped(json, false);
}

export function ProjectStatisticsToJSONTyped(value?: ProjectStatistics | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    project: ProjectToJSON(value["project"]),
    totalEstimatedCost: value["totalEstimatedCost"],
    totalRealCost: value["totalRealCost"],
    remainingBudget: value["remainingBudget"],
    transactionCount: value["transactionCount"],
  };
}
