/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SignUpCredentials
 */
export interface SignUpCredentials {
  /**
   *
   * @type {string}
   * @memberof SignUpCredentials
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof SignUpCredentials
   */
  password?: string;
  /**
   *
   * @type {string}
   * @memberof SignUpCredentials
   */
  username?: string;
}

/**
 * Check if a given object implements the SignUpCredentials interface.
 */
export function instanceOfSignUpCredentials(value: object): value is SignUpCredentials {
  return true;
}

export function SignUpCredentialsFromJSON(json: any): SignUpCredentials {
  return SignUpCredentialsFromJSONTyped(json, false);
}

export function SignUpCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpCredentials {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"] == null ? undefined : json["email"],
    password: json["password"] == null ? undefined : json["password"],
    username: json["username"] == null ? undefined : json["username"],
  };
}

export function SignUpCredentialsToJSON(json: any): SignUpCredentials {
  return SignUpCredentialsToJSONTyped(json, false);
}

export function SignUpCredentialsToJSONTyped(value?: SignUpCredentials | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
    username: value["username"],
  };
}
