/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { SignUpResult } from "./SignUpResult";
import { SignUpResultFromJSON, SignUpResultFromJSONTyped, SignUpResultToJSON, SignUpResultToJSONTyped } from "./SignUpResult";

/**
 *
 * @export
 * @interface SignInResult
 */
export interface SignInResult {
  /**
   *
   * @type {SignUpResult}
   * @memberof SignInResult
   */
  account?: SignUpResult;
  /**
   *
   * @type {string}
   * @memberof SignInResult
   */
  token?: string;
}

/**
 * Check if a given object implements the SignInResult interface.
 */
export function instanceOfSignInResult(value: object): value is SignInResult {
  return true;
}

export function SignInResultFromJSON(json: any): SignInResult {
  return SignInResultFromJSONTyped(json, false);
}

export function SignInResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInResult {
  if (json == null) {
    return json;
  }
  return {
    account: json["account"] == null ? undefined : SignUpResultFromJSON(json["account"]),
    token: json["token"] == null ? undefined : json["token"],
  };
}

export function SignInResultToJSON(json: any): SignInResult {
  return SignInResultToJSONTyped(json, false);
}

export function SignInResultToJSONTyped(value?: SignInResult | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    account: SignUpResultToJSON(value["account"]),
    token: value["token"],
  };
}
