/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SignUpResult
 */
export interface SignUpResult {
  /**
   *
   * @type {string}
   * @memberof SignUpResult
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof SignUpResult
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof SignUpResult
   */
  email?: string;
}

/**
 * Check if a given object implements the SignUpResult interface.
 */
export function instanceOfSignUpResult(value: object): value is SignUpResult {
  return true;
}

export function SignUpResultFromJSON(json: any): SignUpResult {
  return SignUpResultFromJSONTyped(json, false);
}

export function SignUpResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpResult {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    username: json["username"] == null ? undefined : json["username"],
    email: json["email"] == null ? undefined : json["email"],
  };
}

export function SignUpResultToJSON(json: any): SignUpResult {
  return SignUpResultToJSONTyped(json, false);
}

export function SignUpResultToJSONTyped(value?: SignUpResult | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    username: value["username"],
    email: value["email"],
  };
}
