/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SubscriptionResult
 */
export interface SubscriptionResult {
  /**
   *
   * @type {string}
   * @memberof SubscriptionResult
   */
  token?: string;
  /**
   *
   * @type {Date}
   * @memberof SubscriptionResult
   */
  endingDate?: Date;
}

/**
 * Check if a given object implements the SubscriptionResult interface.
 */
export function instanceOfSubscriptionResult(value: object): value is SubscriptionResult {
  return true;
}

export function SubscriptionResultFromJSON(json: any): SubscriptionResult {
  return SubscriptionResultFromJSONTyped(json, false);
}

export function SubscriptionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResult {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"] == null ? undefined : json["token"],
    endingDate: json["endingDate"] == null ? undefined : new Date(json["endingDate"]),
  };
}

export function SubscriptionResultToJSON(json: any): SubscriptionResult {
  return SubscriptionResultToJSONTyped(json, false);
}

export function SubscriptionResultToJSONTyped(value?: SubscriptionResult | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
    endingDate: value["endingDate"] == null ? value["endingDate"] : value["endingDate"].toISOString(),
  };
}
