/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Label } from "./Label";
import { LabelFromJSON, LabelFromJSONTyped, LabelToJSON, LabelToJSONTyped } from "./Label";

/**
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   *
   * @type {Date}
   * @memberof Transaction
   */
  date?: Date;
  /**
   *
   * @type {Array<Label>}
   * @memberof Transaction
   */
  labels?: Array<Label>;
  /**
   *
   * @type {TransactionTypeEnum}
   * @memberof Transaction
   */
  type?: TransactionTypeEnum;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  amount?: number;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  walletId?: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  accountId?: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  goalId?: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  id?: string;
}

/**
 * @export
 */
export const TransactionTypeEnum = {
  In: "IN",
  Out: "OUT",
} as const;
export type TransactionTypeEnum = (typeof TransactionTypeEnum)[keyof typeof TransactionTypeEnum];

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
  return true;
}

export function TransactionFromJSON(json: any): Transaction {
  return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
  if (json == null) {
    return json;
  }
  return {
    date: json["date"] == null ? undefined : new Date(json["date"]),
    labels: json["labels"] == null ? undefined : (json["labels"] as Array<any>).map(LabelFromJSON),
    type: json["type"] == null ? undefined : json["type"],
    description: json["description"] == null ? undefined : json["description"],
    amount: json["amount"] == null ? undefined : json["amount"],
    walletId: json["walletId"] == null ? undefined : json["walletId"],
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    goalId: json["goalId"] == null ? undefined : json["goalId"],
    id: json["id"] == null ? undefined : json["id"],
  };
}

export function TransactionToJSON(json: any): Transaction {
  return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Transaction | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    date: value["date"] == null ? value["date"] : value["date"].toISOString(),
    labels: value["labels"] == null ? undefined : (value["labels"] as Array<any>).map(LabelToJSON),
    type: value["type"],
    description: value["description"],
    amount: value["amount"],
    walletId: value["walletId"],
    accountId: value["accountId"],
    goalId: value["goalId"],
    id: value["id"],
  };
}
