/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface TransactionConfiguration
 */
export interface TransactionConfiguration {
  /**
   * Time, day, month or year transaction notification reccurency
   * @type {number}
   * @memberof TransactionConfiguration
   */
  reccurency?: number;
  /**
   * Time, day, month or year transaction get to make notification
   * @type {number}
   * @memberof TransactionConfiguration
   */
  countDays?: number;
}

/**
 * Check if a given object implements the TransactionConfiguration interface.
 */
export function instanceOfTransactionConfiguration(value: object): value is TransactionConfiguration {
  return true;
}

export function TransactionConfigurationFromJSON(json: any): TransactionConfiguration {
  return TransactionConfigurationFromJSONTyped(json, false);
}

export function TransactionConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionConfiguration {
  if (json == null) {
    return json;
  }
  return {
    reccurency: json["reccurency"] == null ? undefined : json["reccurency"],
    countDays: json["countDays"] == null ? undefined : json["countDays"],
  };
}

export function TransactionConfigurationToJSON(json: any): TransactionConfiguration {
  return TransactionConfigurationToJSONTyped(json, false);
}

export function TransactionConfigurationToJSONTyped(value?: TransactionConfiguration | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    reccurency: value["reccurency"],
    countDays: value["countDays"],
  };
}
