/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface UpdateWallet
 */
export interface UpdateWallet {
  /**
   *
   * @type {string}
   * @memberof UpdateWallet
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateWallet
   */
  description?: string;
  /**
   *
   * @type {UpdateWalletTypeEnum}
   * @memberof UpdateWallet
   */
  type?: UpdateWalletTypeEnum;
  /**
   *
   * @type {string}
   * @memberof UpdateWallet
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateWallet
   */
  iconRef?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateWallet
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateWallet
   */
  accountId?: string;
  /**
   *
   * @type {boolean}
   * @memberof UpdateWallet
   */
  isActive?: boolean;
}

/**
 * @export
 */
export const UpdateWalletTypeEnum = {
  Cash: "CASH",
  MobileMoney: "MOBILE_MONEY",
  Bank: "BANK",
  Debt: "DEBT",
} as const;
export type UpdateWalletTypeEnum = (typeof UpdateWalletTypeEnum)[keyof typeof UpdateWalletTypeEnum];

/**
 * Check if a given object implements the UpdateWallet interface.
 */
export function instanceOfUpdateWallet(value: object): value is UpdateWallet {
  return true;
}

export function UpdateWalletFromJSON(json: any): UpdateWallet {
  return UpdateWalletFromJSONTyped(json, false);
}

export function UpdateWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWallet {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    type: json["type"] == null ? undefined : json["type"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
    id: json["id"] == null ? undefined : json["id"],
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    isActive: json["isActive"] == null ? undefined : json["isActive"],
  };
}

export function UpdateWalletToJSON(json: any): UpdateWallet {
  return UpdateWalletToJSONTyped(json, false);
}

export function UpdateWalletToJSONTyped(value?: UpdateWallet | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    type: value["type"],
    color: value["color"],
    iconRef: value["iconRef"],
    id: value["id"],
    accountId: value["accountId"],
    isActive: value["isActive"],
  };
}
