/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface WalletAutomaticIncome
 */
export interface WalletAutomaticIncome {
  /**
   *
   * @type {WalletAutomaticIncomeTypeEnum}
   * @memberof WalletAutomaticIncome
   */
  type?: WalletAutomaticIncomeTypeEnum;
  /**
   *
   * @type {number}
   * @memberof WalletAutomaticIncome
   */
  amount?: number;
  /**
   * one day in a month where the new payment will be add to the current wallet
   * only work if the type is MENSUAL
   *
   * @type {number}
   * @memberof WalletAutomaticIncome
   */
  paymentDay?: number;
}

/**
 * @export
 */
export const WalletAutomaticIncomeTypeEnum = {
  NotSpecified: "NOT_SPECIFIED",
  Mensual: "MENSUAL",
} as const;
export type WalletAutomaticIncomeTypeEnum = (typeof WalletAutomaticIncomeTypeEnum)[keyof typeof WalletAutomaticIncomeTypeEnum];

/**
 * Check if a given object implements the WalletAutomaticIncome interface.
 */
export function instanceOfWalletAutomaticIncome(value: object): value is WalletAutomaticIncome {
  return true;
}

export function WalletAutomaticIncomeFromJSON(json: any): WalletAutomaticIncome {
  return WalletAutomaticIncomeFromJSONTyped(json, false);
}

export function WalletAutomaticIncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletAutomaticIncome {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"] == null ? undefined : json["type"],
    amount: json["amount"] == null ? undefined : json["amount"],
    paymentDay: json["paymentDay"] == null ? undefined : json["paymentDay"],
  };
}

export function WalletAutomaticIncomeToJSON(json: any): WalletAutomaticIncome {
  return WalletAutomaticIncomeToJSONTyped(json, false);
}

export function WalletAutomaticIncomeToJSONTyped(value?: WalletAutomaticIncome | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    amount: value["amount"],
    paymentDay: value["paymentDay"],
  };
}
