/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { WalletAutomaticIncome } from "./WalletAutomaticIncome";
import { WalletAutomaticIncomeFromJSON, WalletAutomaticIncomeFromJSONTyped, WalletAutomaticIncomeToJSON, WalletAutomaticIncomeToJSONTyped } from "./WalletAutomaticIncome";

/**
 *
 * @export
 * @interface Wallet
 */
export interface Wallet {
  /**
   *
   * @type {string}
   * @memberof Wallet
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Wallet
   */
  description?: string;
  /**
   *
   * @type {WalletTypeEnum}
   * @memberof Wallet
   */
  type?: WalletTypeEnum;
  /**
   *
   * @type {string}
   * @memberof Wallet
   */
  color?: string;
  /**
   *
   * @type {string}
   * @memberof Wallet
   */
  iconRef?: string;
  /**
   *
   * @type {string}
   * @memberof Wallet
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Wallet
   */
  accountId?: string;
  /**
   *
   * @type {boolean}
   * @memberof Wallet
   */
  isActive?: boolean;
  /**
   *
   * @type {number}
   * @memberof Wallet
   */
  amount?: number;
  /**
   *
   * @type {WalletAutomaticIncome}
   * @memberof Wallet
   */
  walletAutomaticIncome?: WalletAutomaticIncome;
}

/**
 * @export
 */
export const WalletTypeEnum = {
  Cash: "CASH",
  MobileMoney: "MOBILE_MONEY",
  Bank: "BANK",
  Debt: "DEBT",
} as const;
export type WalletTypeEnum = (typeof WalletTypeEnum)[keyof typeof WalletTypeEnum];

/**
 * Check if a given object implements the Wallet interface.
 */
export function instanceOfWallet(value: object): value is Wallet {
  return true;
}

export function WalletFromJSON(json: any): Wallet {
  return WalletFromJSONTyped(json, false);
}

export function WalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallet {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    description: json["description"] == null ? undefined : json["description"],
    type: json["type"] == null ? undefined : json["type"],
    color: json["color"] == null ? undefined : json["color"],
    iconRef: json["iconRef"] == null ? undefined : json["iconRef"],
    id: json["id"] == null ? undefined : json["id"],
    accountId: json["accountId"] == null ? undefined : json["accountId"],
    isActive: json["isActive"] == null ? undefined : json["isActive"],
    amount: json["amount"] == null ? undefined : json["amount"],
    walletAutomaticIncome: json["walletAutomaticIncome"] == null ? undefined : WalletAutomaticIncomeFromJSON(json["walletAutomaticIncome"]),
  };
}

export function WalletToJSON(json: any): Wallet {
  return WalletToJSONTyped(json, false);
}

export function WalletToJSONTyped(value?: Wallet | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    description: value["description"],
    type: value["type"],
    color: value["color"],
    iconRef: value["iconRef"],
    id: value["id"],
    accountId: value["accountId"],
    isActive: value["isActive"],
    amount: value["amount"],
    walletAutomaticIncome: WalletAutomaticIncomeToJSON(value["walletAutomaticIncome"]),
  };
}
