/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { GoogleSignInRequest, SignInCredentials, SignInResult, SignUpCredentials, SignUpResult } from "../models/index";
import {
  GoogleSignInRequestFromJSON,
  GoogleSignInRequestToJSON,
  SignInCredentialsFromJSON,
  SignInCredentialsToJSON,
  SignInResultFromJSON,
  SignInResultToJSON,
  SignUpCredentialsFromJSON,
  SignUpCredentialsToJSON,
  SignUpResultFromJSON,
  SignUpResultToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface GoogleSignInOperationRequest {
  googleSignInRequest?: GoogleSignInRequest;
}

export interface SignInRequest {
  signInCredentials?: SignInCredentials;
}

export interface SignUpRequest {
  signUpCredentials?: SignUpCredentials;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for googleSignIn without sending the request
   */
  async googleSignInRequestOpts(requestParameters: GoogleSignInOperationRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/google`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: GoogleSignInRequestToJSON(requestParameters["googleSignInRequest"]),
    };
  }

  /**
   * Authenticate with Google
   */
  async googleSignInRaw(requestParameters: GoogleSignInOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignInResult>> {
    const requestOptions = await this.googleSignInRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => SignInResultFromJSON(jsonValue));
  }

  /**
   * Authenticate with Google
   */
  async googleSignIn(requestParameters: GoogleSignInOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignInResult> {
    const response = await this.googleSignInRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for signIn without sending the request
   */
  async signInRequestOpts(requestParameters: SignInRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/sign-in`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: SignInCredentialsToJSON(requestParameters["signInCredentials"]),
    };
  }

  /**
   * Login with and existing account
   */
  async signInRaw(requestParameters: SignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignInResult>> {
    const requestOptions = await this.signInRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => SignInResultFromJSON(jsonValue));
  }

  /**
   * Login with and existing account
   */
  async signIn(requestParameters: SignInRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignInResult> {
    const response = await this.signInRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for signUp without sending the request
   */
  async signUpRequestOpts(requestParameters: SignUpRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/sign-up`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: SignUpCredentialsToJSON(requestParameters["signUpCredentials"]),
    };
  }

  /**
   * Create new account with basic user role
   */
  async signUpRaw(requestParameters: SignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignUpResult>> {
    const requestOptions = await this.signUpRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => SignUpResultFromJSON(jsonValue));
  }

  /**
   * Create new account with basic user role
   */
  async signUp(requestParameters: SignUpRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignUpResult> {
    const response = await this.signUpRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
