/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationGoal, GetAllGoals200Response, Goal } from "../models/index";
import { CreationGoalFromJSON, CreationGoalToJSON, GetAllGoals200ResponseFromJSON, GetAllGoals200ResponseToJSON, GoalFromJSON, GoalToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface ArchiveOneGoalRequest {
  accountId: string;
  labelId: string;
  walletId: string;
}

export interface CreateOneGoalRequest {
  accountId: string;
  walletId: string;
  creationGoal?: CreationGoal;
}

export interface GetAllGoalsRequest {
  accountId: string;
  walletId?: string;
  name?: string;
  minAmount?: number;
  maxAmount?: number;
  startingDateBeginning?: Date;
  startingDateEnding?: Date;
  endingDateBeginning?: Date;
  endingDateEnding?: Date;
  sort?: GetAllGoalsSortEnum;
}

export interface GetOneGoalRequest {
  accountId: string;
  walletId: string;
  goalId: string;
}

export interface UpdateOneGoalRequest {
  accountId: string;
  walletId: string;
  goalId: string;
  goal?: Goal;
}

/**
 *
 */
export class GoalApi extends runtime.BaseAPI {
  /**
   * Creates request options for archiveOneGoal without sending the request
   */
  async archiveOneGoalRequestOpts(requestParameters: ArchiveOneGoalRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling archiveOneGoal().');
    }

    if (requestParameters["labelId"] == null) {
      throw new runtime.RequiredError("labelId", 'Required parameter "labelId" was null or undefined when calling archiveOneGoal().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling archiveOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/wallet/{walletId}/goal/{goalId}/archive`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"labelId"}}`, encodeURIComponent(String(requestParameters["labelId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Archive one label by id
   */
  async archiveOneGoalRaw(requestParameters: ArchiveOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
    const requestOptions = await this.archiveOneGoalRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * Archive one label by id
   */
  async archiveOneGoal(requestParameters: ArchiveOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.archiveOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createOneGoal without sending the request
   */
  async createOneGoalRequestOpts(requestParameters: CreateOneGoalRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneGoal().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling createOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet/{walletId}/goal`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreationGoalToJSON(requestParameters["creationGoal"]),
    };
  }

  /**
   * create new goal for one account
   */
  async createOneGoalRaw(
    requestParameters: CreateOneGoalRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetAllGoals200Response>> {
    const requestOptions = await this.createOneGoalRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => GetAllGoals200ResponseFromJSON(jsonValue));
  }

  /**
   * create new goal for one account
   */
  async createOneGoal(requestParameters: CreateOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllGoals200Response> {
    const response = await this.createOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getAllGoals without sending the request
   */
  async getAllGoalsRequestOpts(requestParameters: GetAllGoalsRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllGoals().');
    }

    const queryParameters: any = {};

    if (requestParameters["walletId"] != null) {
      queryParameters["walletId"] = requestParameters["walletId"];
    }

    if (requestParameters["name"] != null) {
      queryParameters["name"] = requestParameters["name"];
    }

    if (requestParameters["minAmount"] != null) {
      queryParameters["minAmount"] = requestParameters["minAmount"];
    }

    if (requestParameters["maxAmount"] != null) {
      queryParameters["maxAmount"] = requestParameters["maxAmount"];
    }

    if (requestParameters["startingDateBeginning"] != null) {
      queryParameters["startingDateBeginning"] = (requestParameters["startingDateBeginning"] as any).toISOString();
    }

    if (requestParameters["startingDateEnding"] != null) {
      queryParameters["startingDateEnding"] = (requestParameters["startingDateEnding"] as any).toISOString();
    }

    if (requestParameters["endingDateBeginning"] != null) {
      queryParameters["endingDateBeginning"] = (requestParameters["endingDateBeginning"] as any).toISOString();
    }

    if (requestParameters["endingDateEnding"] != null) {
      queryParameters["endingDateEnding"] = (requestParameters["endingDateEnding"] as any).toISOString();
    }

    if (requestParameters["sort"] != null) {
      queryParameters["sort"] = requestParameters["sort"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/goal`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get all disponibles goal of one account
   */
  async getAllGoalsRaw(requestParameters: GetAllGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllGoals200Response>> {
    const requestOptions = await this.getAllGoalsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => GetAllGoals200ResponseFromJSON(jsonValue));
  }

  /**
   * Get all disponibles goal of one account
   */
  async getAllGoals(requestParameters: GetAllGoalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllGoals200Response> {
    const response = await this.getAllGoalsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getOneGoal without sending the request
   */
  async getOneGoalRequestOpts(requestParameters: GetOneGoalRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneGoal().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling getOneGoal().');
    }

    if (requestParameters["goalId"] == null) {
      throw new runtime.RequiredError("goalId", 'Required parameter "goalId" was null or undefined when calling getOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/wallet/{walletId}/goal/{goalId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));
    urlPath = urlPath.replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters["goalId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get one goal of one account by it\'s id
   */
  async getOneGoalRaw(requestParameters: GetOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
    const requestOptions = await this.getOneGoalRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * Get one goal of one account by it\'s id
   */
  async getOneGoal(requestParameters: GetOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.getOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateOneGoal without sending the request
   */
  async updateOneGoalRequestOpts(requestParameters: UpdateOneGoalRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneGoal().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling updateOneGoal().');
    }

    if (requestParameters["goalId"] == null) {
      throw new runtime.RequiredError("goalId", 'Required parameter "goalId" was null or undefined when calling updateOneGoal().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet/{walletId}/goal/{goalId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));
    urlPath = urlPath.replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters["goalId"])));

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: GoalToJSON(requestParameters["goal"]),
    };
  }

  /**
   * update one goal of one account
   */
  async updateOneGoalRaw(requestParameters: UpdateOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
    const requestOptions = await this.updateOneGoalRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * update one goal of one account
   */
  async updateOneGoal(requestParameters: UpdateOneGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.updateOneGoalRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const GetAllGoalsSortEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetAllGoalsSortEnum = (typeof GetAllGoalsSortEnum)[keyof typeof GetAllGoalsSortEnum];
