/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationLabel, GetAllLabels200Response, Label } from "../models/index";
import { CreationLabelFromJSON, CreationLabelToJSON, GetAllLabels200ResponseFromJSON, GetAllLabels200ResponseToJSON, LabelFromJSON, LabelToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface ArchiveOneLabelRequest {
  accountId: string;
  labelId: string;
}

export interface CreateOneLabelRequest {
  accountId: string;
  creationLabel?: CreationLabel;
}

export interface GetAllLabelsRequest {
  accountId: string;
  page?: number;
  pageSize?: number;
  name?: string;
}

export interface GetOneLabelRequest {
  accountId: string;
  labelId: string;
}

export interface UpdateOneLabelRequest {
  accountId: string;
  labelId: string;
  label?: Label;
}

/**
 *
 */
export class LabelApi extends runtime.BaseAPI {
  /**
   * Creates request options for archiveOneLabel without sending the request
   */
  async archiveOneLabelRequestOpts(requestParameters: ArchiveOneLabelRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling archiveOneLabel().');
    }

    if (requestParameters["labelId"] == null) {
      throw new runtime.RequiredError("labelId", 'Required parameter "labelId" was null or undefined when calling archiveOneLabel().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/label/{labelId}/archive`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"labelId"}}`, encodeURIComponent(String(requestParameters["labelId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Archive one label by id
   */
  async archiveOneLabelRaw(requestParameters: ArchiveOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    const requestOptions = await this.archiveOneLabelRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Archive one label by id
   */
  async archiveOneLabel(requestParameters: ArchiveOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.archiveOneLabelRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createOneLabel without sending the request
   */
  async createOneLabelRequestOpts(requestParameters: CreateOneLabelRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneLabel().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/label`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreationLabelToJSON(requestParameters["creationLabel"]),
    };
  }

  /**
   * Create new label for the specified account
   */
  async createOneLabelRaw(requestParameters: CreateOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    const requestOptions = await this.createOneLabelRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Create new label for the specified account
   */
  async createOneLabel(requestParameters: CreateOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.createOneLabelRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getAllLabels without sending the request
   */
  async getAllLabelsRequestOpts(requestParameters: GetAllLabelsRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllLabels().');
    }

    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["pageSize"] != null) {
      queryParameters["pageSize"] = requestParameters["pageSize"];
    }

    if (requestParameters["name"] != null) {
      queryParameters["name"] = requestParameters["name"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/label`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get all disponibles lables for the specified account
   */
  async getAllLabelsRaw(requestParameters: GetAllLabelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAllLabels200Response>> {
    const requestOptions = await this.getAllLabelsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => GetAllLabels200ResponseFromJSON(jsonValue));
  }

  /**
   * Get all disponibles lables for the specified account
   */
  async getAllLabels(requestParameters: GetAllLabelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAllLabels200Response> {
    const response = await this.getAllLabelsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getOneLabel without sending the request
   */
  async getOneLabelRequestOpts(requestParameters: GetOneLabelRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneLabel().');
    }

    if (requestParameters["labelId"] == null) {
      throw new runtime.RequiredError("labelId", 'Required parameter "labelId" was null or undefined when calling getOneLabel().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/label/{labelId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"labelId"}}`, encodeURIComponent(String(requestParameters["labelId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get get one label by id for the specified account
   */
  async getOneLabelRaw(requestParameters: GetOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    const requestOptions = await this.getOneLabelRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Get get one label by id for the specified account
   */
  async getOneLabel(requestParameters: GetOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.getOneLabelRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateOneLabel without sending the request
   */
  async updateOneLabelRequestOpts(requestParameters: UpdateOneLabelRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneLabel().');
    }

    if (requestParameters["labelId"] == null) {
      throw new runtime.RequiredError("labelId", 'Required parameter "labelId" was null or undefined when calling updateOneLabel().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/label/{labelId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"labelId"}}`, encodeURIComponent(String(requestParameters["labelId"])));

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: LabelToJSON(requestParameters["label"]),
    };
  }

  /**
   * Update one label by id for the specified account
   */
  async updateOneLabelRaw(requestParameters: UpdateOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Label>> {
    const requestOptions = await this.updateOneLabelRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LabelFromJSON(jsonValue));
  }

  /**
   * Update one label by id for the specified account
   */
  async updateOneLabel(requestParameters: UpdateOneLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Label> {
    const response = await this.updateOneLabelRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
