/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationProject, CreationProjectTransaction, Project, ProjectStatistics, ProjectTransaction } from "../models/index";
import {
  CreationProjectFromJSON,
  CreationProjectToJSON,
  CreationProjectTransactionFromJSON,
  CreationProjectTransactionToJSON,
  ProjectFromJSON,
  ProjectStatisticsFromJSON,
  ProjectStatisticsToJSON,
  ProjectToJSON,
  ProjectTransactionFromJSON,
  ProjectTransactionToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ArchiveOneProjectRequest {
  accountId: string;
  projectId: string;
}

export interface CreateOneProjectRequest {
  accountId: string;
  creationProject?: CreationProject;
}

export interface CreateOneProjectTransactionRequest {
  accountId: string;
  projectId: string;
  creationProjectTransaction?: CreationProjectTransaction;
}

export interface DeleteOneProjectRequest {
  accountId: string;
  projectId: string;
}

export interface DeleteOneProjectTransactionRequest {
  accountId: string;
  projectId: string;
  transactionId: string;
}

export interface DownloadProjectInvoicePDFRequest {
  accountId: string;
  projectId: string;
}

export interface DownloadProjectStatisticsPDFRequest {
  accountId: string;
  projectId: string;
}

export interface DownloadProjectSummaryPDFRequest {
  accountId: string;
  projectId: string;
}

export interface GetAllProjectTransactionsRequest {
  accountId: string;
  projectId: string;
}

export interface GetAllProjectsRequest {
  accountId: string;
  page?: number;
  pageSize?: number;
  name?: string;
}

export interface GetOneProjectRequest {
  accountId: string;
  projectId: string;
}

export interface GetOneProjectTransactionRequest {
  accountId: string;
  projectId: string;
  transactionId: string;
}

export interface GetProjectStatisticsRequest {
  accountId: string;
  projectId: string;
}

export interface UpdateOneProjectRequest {
  accountId: string;
  projectId: string;
  creationProject?: CreationProject;
}

export interface UpdateOneProjectTransactionRequest {
  accountId: string;
  projectId: string;
  transactionId: string;
  creationProjectTransaction?: CreationProjectTransaction;
}

/**
 *
 */
export class ProjectApi extends runtime.BaseAPI {
  /**
   * Creates request options for archiveOneProject without sending the request
   */
  async archiveOneProjectRequestOpts(requestParameters: ArchiveOneProjectRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling archiveOneProject().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling archiveOneProject().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/archive`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Archive one project by id
   */
  async archiveOneProjectRaw(requestParameters: ArchiveOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
    const requestOptions = await this.archiveOneProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Archive one project by id
   */
  async archiveOneProject(requestParameters: ArchiveOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
    const response = await this.archiveOneProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createOneProject without sending the request
   */
  async createOneProjectRequestOpts(requestParameters: CreateOneProjectRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneProject().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/project`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreationProjectToJSON(requestParameters["creationProject"]),
    };
  }

  /**
   * Create new project for the specified account
   */
  async createOneProjectRaw(requestParameters: CreateOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
    const requestOptions = await this.createOneProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Create new project for the specified account
   */
  async createOneProject(requestParameters: CreateOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
    const response = await this.createOneProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createOneProjectTransaction without sending the request
   */
  async createOneProjectTransactionRequestOpts(requestParameters: CreateOneProjectTransactionRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneProjectTransaction().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling createOneProjectTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/project/{projectId}/transaction`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreationProjectTransactionToJSON(requestParameters["creationProjectTransaction"]),
    };
  }

  /**
   * Create new project transaction for the specified account
   */
  async createOneProjectTransactionRaw(
    requestParameters: CreateOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProjectTransaction>> {
    const requestOptions = await this.createOneProjectTransactionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectTransactionFromJSON(jsonValue));
  }

  /**
   * Create new project transaction for the specified account
   */
  async createOneProjectTransaction(
    requestParameters: CreateOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProjectTransaction> {
    const response = await this.createOneProjectTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteOneProject without sending the request
   */
  async deleteOneProjectRequestOpts(requestParameters: DeleteOneProjectRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling deleteOneProject().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling deleteOneProject().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete one project by id for the specified account
   */
  async deleteOneProjectRaw(requestParameters: DeleteOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
    const requestOptions = await this.deleteOneProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Delete one project by id for the specified account
   */
  async deleteOneProject(requestParameters: DeleteOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
    const response = await this.deleteOneProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteOneProjectTransaction without sending the request
   */
  async deleteOneProjectTransactionRequestOpts(requestParameters: DeleteOneProjectTransactionRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling deleteOneProjectTransaction().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling deleteOneProjectTransaction().');
    }

    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError("transactionId", 'Required parameter "transactionId" was null or undefined when calling deleteOneProjectTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete one project transaction by id
   */
  async deleteOneProjectTransactionRaw(
    requestParameters: DeleteOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProjectTransaction>> {
    const requestOptions = await this.deleteOneProjectTransactionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectTransactionFromJSON(jsonValue));
  }

  /**
   * Delete one project transaction by id
   */
  async deleteOneProjectTransaction(
    requestParameters: DeleteOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProjectTransaction> {
    const response = await this.deleteOneProjectTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for downloadProjectInvoicePDF without sending the request
   */
  async downloadProjectInvoicePDFRequestOpts(requestParameters: DownloadProjectInvoicePDFRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling downloadProjectInvoicePDF().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling downloadProjectInvoicePDF().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/pdf/invoice`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Download project invoice as PDF
   */
  async downloadProjectInvoicePDFRaw(
    requestParameters: DownloadProjectInvoicePDFRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Blob>> {
    const requestOptions = await this.downloadProjectInvoicePDFRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Download project invoice as PDF
   */
  async downloadProjectInvoicePDF(requestParameters: DownloadProjectInvoicePDFRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
    const response = await this.downloadProjectInvoicePDFRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for downloadProjectStatisticsPDF without sending the request
   */
  async downloadProjectStatisticsPDFRequestOpts(requestParameters: DownloadProjectStatisticsPDFRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling downloadProjectStatisticsPDF().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling downloadProjectStatisticsPDF().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/pdf/statistics`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Download project statistics as PDF
   */
  async downloadProjectStatisticsPDFRaw(
    requestParameters: DownloadProjectStatisticsPDFRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Blob>> {
    const requestOptions = await this.downloadProjectStatisticsPDFRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Download project statistics as PDF
   */
  async downloadProjectStatisticsPDF(requestParameters: DownloadProjectStatisticsPDFRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
    const response = await this.downloadProjectStatisticsPDFRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for downloadProjectSummaryPDF without sending the request
   */
  async downloadProjectSummaryPDFRequestOpts(requestParameters: DownloadProjectSummaryPDFRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling downloadProjectSummaryPDF().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling downloadProjectSummaryPDF().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/pdf/summary`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Download project summary as PDF
   */
  async downloadProjectSummaryPDFRaw(
    requestParameters: DownloadProjectSummaryPDFRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Blob>> {
    const requestOptions = await this.downloadProjectSummaryPDFRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Download project summary as PDF
   */
  async downloadProjectSummaryPDF(requestParameters: DownloadProjectSummaryPDFRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
    const response = await this.downloadProjectSummaryPDFRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getAllProjectTransactions without sending the request
   */
  async getAllProjectTransactionsRequestOpts(requestParameters: GetAllProjectTransactionsRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllProjectTransactions().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling getAllProjectTransactions().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/transaction`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get all project transactions for the specified project
   */
  async getAllProjectTransactionsRaw(
    requestParameters: GetAllProjectTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ProjectTransaction>>> {
    const requestOptions = await this.getAllProjectTransactionsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectTransactionFromJSON));
  }

  /**
   * Get all project transactions for the specified project
   */
  async getAllProjectTransactions(
    requestParameters: GetAllProjectTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ProjectTransaction>> {
    const response = await this.getAllProjectTransactionsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getAllProjects without sending the request
   */
  async getAllProjectsRequestOpts(requestParameters: GetAllProjectsRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllProjects().');
    }

    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["pageSize"] != null) {
      queryParameters["pageSize"] = requestParameters["pageSize"];
    }

    if (requestParameters["name"] != null) {
      queryParameters["name"] = requestParameters["name"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get all projects for the specified account
   */
  async getAllProjectsRaw(requestParameters: GetAllProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>> {
    const requestOptions = await this.getAllProjectsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectFromJSON));
  }

  /**
   * Get all projects for the specified account
   */
  async getAllProjects(requestParameters: GetAllProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>> {
    const response = await this.getAllProjectsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getOneProject without sending the request
   */
  async getOneProjectRequestOpts(requestParameters: GetOneProjectRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneProject().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling getOneProject().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get one project by id for the specified account
   */
  async getOneProjectRaw(requestParameters: GetOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
    const requestOptions = await this.getOneProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Get one project by id for the specified account
   */
  async getOneProject(requestParameters: GetOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
    const response = await this.getOneProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getOneProjectTransaction without sending the request
   */
  async getOneProjectTransactionRequestOpts(requestParameters: GetOneProjectTransactionRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneProjectTransaction().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling getOneProjectTransaction().');
    }

    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError("transactionId", 'Required parameter "transactionId" was null or undefined when calling getOneProjectTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get one project transaction by id
   */
  async getOneProjectTransactionRaw(
    requestParameters: GetOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProjectTransaction>> {
    const requestOptions = await this.getOneProjectTransactionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectTransactionFromJSON(jsonValue));
  }

  /**
   * Get one project transaction by id
   */
  async getOneProjectTransaction(requestParameters: GetOneProjectTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectTransaction> {
    const response = await this.getOneProjectTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getProjectStatistics without sending the request
   */
  async getProjectStatisticsRequestOpts(requestParameters: GetProjectStatisticsRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getProjectStatistics().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling getProjectStatistics().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/project/{projectId}/statistics`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get statistics for one project
   */
  async getProjectStatisticsRaw(
    requestParameters: GetProjectStatisticsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProjectStatistics>> {
    const requestOptions = await this.getProjectStatisticsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectStatisticsFromJSON(jsonValue));
  }

  /**
   * Get statistics for one project
   */
  async getProjectStatistics(requestParameters: GetProjectStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectStatistics> {
    const response = await this.getProjectStatisticsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateOneProject without sending the request
   */
  async updateOneProjectRequestOpts(requestParameters: UpdateOneProjectRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneProject().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling updateOneProject().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/project/{projectId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: CreationProjectToJSON(requestParameters["creationProject"]),
    };
  }

  /**
   * Update one project by id for the specified account
   */
  async updateOneProjectRaw(requestParameters: UpdateOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Project>> {
    const requestOptions = await this.updateOneProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Update one project by id for the specified account
   */
  async updateOneProject(requestParameters: UpdateOneProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Project> {
    const response = await this.updateOneProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateOneProjectTransaction without sending the request
   */
  async updateOneProjectTransactionRequestOpts(requestParameters: UpdateOneProjectTransactionRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneProjectTransaction().');
    }

    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError("projectId", 'Required parameter "projectId" was null or undefined when calling updateOneProjectTransaction().');
    }

    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError("transactionId", 'Required parameter "transactionId" was null or undefined when calling updateOneProjectTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/project/{projectId}/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters["projectId"])));
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: CreationProjectTransactionToJSON(requestParameters["creationProjectTransaction"]),
    };
  }

  /**
   * Update one project transaction by id
   */
  async updateOneProjectTransactionRaw(
    requestParameters: UpdateOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProjectTransaction>> {
    const requestOptions = await this.updateOneProjectTransactionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectTransactionFromJSON(jsonValue));
  }

  /**
   * Update one project transaction by id
   */
  async updateOneProjectTransaction(
    requestParameters: UpdateOneProjectTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProjectTransaction> {
    const response = await this.updateOneProjectTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
